# Generated by Django 6.0.3 on 2026-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('generation_mw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(db_index=True)),
                ('target_time', models.DateTimeField(db_index=True)),
                ('generation_mw', models.FloatField()),
            ],
            options={
                'unique_together': {('publish_time', 'target_time')},
            },
        ),
    ]
